In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/Users/olatundeolasunkanmi/Downloads/archive (3).zip_1/fifa21_raw_data.csv', low_memory = False)

In [4]:
df

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Team & Contract   18979 non-null  object
 10  ID                18979 non-null  int64
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  foot              18979 non-null  object
 14  BOV               18979 non-null  int64
 15  BP                18979 non-null  object
 16  Growth            18979 non-null  int64
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              18979 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.1+ MB

In [40]:
pd.set_option('display.max_columns', None)
df.tail(10)

,LongName,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,Weight,foot,BOV,BP,Growth,Joined,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,is_on_loan
18969,Jiyu Zhong,China PR,CM,Zhong Jiyu,23,47,55,\n\n\n\nShijiazhuang Ever Bright F.C.\n2018 ~ ...,255626,"5'7""",137lbs,Right,49,CM,8,"Feb 9, 2018",€45K,€1K,€79K,201,39,30,42,56,34,211,40,39,39,53,40,314,61,65,56,46,86,247,52,64,59,36,36,214,50,38,45,46,35,43,122,38,39,45,51,5,13,7,13,13,1360,277,2 ★,2★,Medium,Low,1 ★,63,37,48,44,39,46,\n4,0
18970,Wenzhuo Huang,China PR,CM,Huang Wenzhou,21,47,53,\n\n\n\nShanghai SIPG FC\n2020 ~ 2022\n\n,257933,"5'9""",150lbs,Right,50,CDM,6,"Aug 1, 2020",€40K,€1K,€72K,193,38,30,42,55,28,212,45,36,36,50,45,291,56,60,50,50,75,211,38,53,48,43,29,220,58,42,32,53,35,35,138,43,42,53,53,8,8,13,14,10,1318,277,2 ★,2★,Low,Low,1 ★,58,32,49,47,43,48,\n2,0
18971,Yue Song,China PR,CM,Song Yue,28,47,47,\n\n\n\nTianjin TEDA FC\n2020 ~ 2022\n\n,257936,"6'1""",174lbs,Right,49,RM,0,"Aug 1, 2020",€30K,€2K,€47K,211,44,32,44,56,35,215,46,37,33,56,43,286,67,64,56,44,55,258,49,59,54,62,34,220,57,35,48,44,36,35,126,38,43,45,36,8,5,11,5,7,1352,296,2 ★,2★,Low,Low,1 ★,65,37,49,46,40,59,\n8,0
18972,Huapeng Wang,China PR,CB,Wang Huapeng,20,47,53,\n\n\n\nGuangzhou R&F FC\n2020 ~ 2022\n\n,257689,"5'11""",170lbs,Right,49,CB,6,"Aug 1, 2020",€35K,€1K,€61K,134,22,18,46,24,24,123,23,27,21,24,28,268,61,57,48,41,61,233,32,68,60,58,15,176,40,44,24,33,35,37,148,41,52,55,58,10,15,12,8,13,1140,238,2 ★,2★,Low,Low,1 ★,59,22,25,30,47,55,\n2,0
18973,Zitong Chen,China PR,CM,Chen Zitong,23,47,51,\n\n\n\nShijiazhuang Ever Bright F.C.\n2020 ~ ...,257697,"6'1""",176lbs,Right,51,CDM,4,"Aug 1, 2020",€40K,€1K,€65K,203,38,32,45,56,32,217,45,35,35,54,48,285,62,60,59,51,53,245,45,56,48,63,33,214,56,40,31,45,42,43,135,41,49,45,47,15,7,7,5,13,1346,294,2 ★,2★,Low,Low,1 ★,61,35,48,48,44,58,\n2,0
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",154lbs,Right,49,CB,5,"Aug 1, 2020",€35K,€1K,€57K,141,23,16,45,31,26,111,19,21,22,25,24,279,60,56,45,48,70,223,35,65,55,45,23,179,44,50,25,25,35,40,148,45,56,47,53,12,13,8,14,6,1134,232,2 ★,2★,Low,Low,1 ★,58,23,26,27,50,48,\n2,0
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",128lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,202,27,47,36,45,47,208,53,43,31,37,44,339,69,70,67,53,80,231,50,50,55,35,41,186,33,11,43,49,50,45,42,18,11,13,48,11,13,9,9,6,1256,265,2 ★,2★,Medium,Medium,1 ★,70,46,40,53,16,40,\n3,0
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",146lbs,Right,49,CB,8,"Jul 13, 2018",€40K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,\n3,0
18977,Ben Hough,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",143lbs,Right,51,CAM,20,"Aug 1, 2020",€60K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,\n5,0
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",150lbs,Right,48,CDM,16,"Jan 1, 2020",€60K,€500,€167K,191,32,27,48,52,32,198,45,31,32,47,43,298,55,59,59,50,75,223,41,55,47,47,33,206,57,45,30,39,35,36,129,43,41,45,56,10,8,15,9,14,1301,273,3 ★,2★,Medium,Medium,1 ★,57,32,43,48,44,49,\n2,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 75 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LongName          18979 non-null  object
 1   Nationality       18979 non-null  object
 2   Positions         18979 non-null  object
 3   Name              18979 non-null  object
 4   Age               18979 non-null  int64
 5   ↓OVA              18979 non-null  int64
 6   POT               18979 non-null  int64
 7   Team & Contract   18979 non-null  object
 8   ID                18979 non-null  int64
 9   Height            18979 non-null  object
 10  Weight            18979 non-null  object
 11  foot              18979 non-null  object
 12  BOV               18979 non-null  int64
 13  BP                18979 non-null  object
 14  Growth            18979 non-null  int64
 15  Joined            18979 non-null  object
 16  Loan Date End     1013 non-null   object
 17  Value             18979 non-null  object
 18  Wage              18979 non-null  object
 19  Release Clause    18979 non-null  object
 20  Attacking         18979 non-null  int64
 21  Crossing          18979 non-null  int64
 22  Finishing         18979 non-null  int64
 23  Heading Accuracy  18979 non-null  int64
 24  Short Passing     18979 non-null  int64
 25  Volleys           18979 non-null  int64
 26  Skill             18979 non-null  int64
 27  Dribbling         18979 non-null  int64
 28  Curve             18979 non-null  int64
 29  FK Accuracy       18979 non-null  int64
 30  Long Passing      18979 non-null  int64
 31  Ball Control      18979 non-null  int64
 32  Movement          18979 non-null  int64
 33  Acceleration      18979 non-null  int64
 34  Sprint Speed      18979 non-null  int64
 35  Agility           18979 non-null  int64
 36  Reactions         18979 non-null  int64
 37  Balance           18979 non-null  int64
 38  Power             18979 non-null  int64
 39  Shot Power        18979 non-null  int64
 40  Jumping           18979 non-null  int64
 41  Stamina           18979 non-null  int64
 42  Strength          18979 non-null  int64
 43  Long Shots        18979 non-null  int64
 44  Mentality         18979 non-null  int64
 45  Aggression        18979 non-null  int64
 46  Interceptions     18979 non-null  int64
 47  Positioning       18979 non-null  int64
 48  Vision            18979 non-null  int64
 49  Penalties         18979 non-null  int64
 50  Composure         18979 non-null  int64
 51  Defending         18979 non-null  int64
 52  Marking           18979 non-null  int64
 53  Standing Tackle   18979 non-null  int64
 54  Sliding Tackle    18979 non-null  int64
 55  Goalkeeping       18979 non-null  int64
 56  GK Diving         18979 non-null  int64
 57  GK Handling       18979 non-null  int64
 58  GK Kicking        18979 non-null  int64
 59  GK Positioning    18979 non-null  int64
 60  GK Reflexes       18979 non-null  int64
 61  Total Stats       18979 non-null  int64
 62  Base Stats        18979 non-null  int64
 63  W/F               18979 non-null  object
 64  SM                18979 non-null  object
 65  A/W               18979 non-null  object
 66  D/W               18979 non-null  object
 67  IR                18979 non-null  object
 68  PAC               18979 non-null  int64
 69  SHO               18979 non-null  int64
 70  PAS               18979 non-null  int64
 71  DRI               18979 non-null  int64
 72  DEF               18979 non-null  int64
 73  PHY               18979 non-null  int64
 74  Hits              18979 non-null  object
dtypes: int64(55), object(20)
memory usage: 10.9+ MB

In [8]:
df.describe()

,Age,↓OVA,POT,ID,BOV,Growth,Attacking,Crossing,Finishing,Heading Accuracy,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,25.194583,65.718636,71.136098,226404.790242,66.751620,5.417461,248.938616,49.688551,45.842932,51.941883,...,16.217609,16.519205,1595.293851,355.703040,67.454239,53.457716,57.681069,62.875494,49.865904,64.368618
std,4.710753,6.968999,6.114176,27141.673349,6.747017,5.663954,74.299764,18.131334,19.566978,17.293626,...,17.002134,17.854185,269.883542,40.762282,10.678058,13.827229,10.081914,9.927875,16.442730,9.601665
min,16.000000,47.000000,47.000000,41.000000,48.000000,0.000000,42.000000,6.000000,3.000000,5.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,21.000000,61.000000,67.000000,210135.000000,62.000000,0.000000,222.000000,38.000000,30.000000,44.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,25.000000,66.000000,71.000000,232424.000000,67.000000,4.000000,263.000000,54.000000,49.000000,55.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,29.000000,70.000000,75.000000,246925.500000,71.000000,9.000000,297.000000,63.000000,62.000000,64.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,53.000000,93.000000,95.000000,259216.000000,93.000000,26.000000,437.000000,94.000000,95.000000,93.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [22]:
pd.set_option('display.max_rows', None)
df.isna().sum()

LongName                0
Nationality             0
Positions               0
Name                    0
Age                     0
↓OVA                    0
POT                     0
Team & Contract         0
ID                      0
Height                  0
Weight                  0
foot                    0
BOV                     0
BP                      0
Growth                  0
Joined                  0
Loan Date End       17966
Value                   0
Wage                    0
Release Clause          0
Attacking               0
Crossing                0
Finishing               0
Heading Accuracy        0
Short Passing           0
Volleys                 0
Skill                   0
Dribbling               0
Curve                   0
FK Accuracy             0
Long Passing            0
Ball Control            0
Movement                0
Acceleration            0
Sprint Speed            0
Agility                 0
Reactions               0
Balance                 0
Power                   0
Shot Power              0
Jumping                 0
Stamina                 0
Strength                0
Long Shots              0
Mentality               0
Aggression              0
Interceptions           0
Positioning             0
Vision                  0
Penalties               0
Composure               0
Defending               0
Marking                 0
Standing Tackle         0
Sliding Tackle          0
Goalkeeping             0
GK Diving               0
GK Handling             0
GK Kicking              0
GK Positioning          0
GK Reflexes             0
Total Stats             0
Base Stats              0
W/F                     0
SM                      0
A/W                     0
D/W                     0
IR                      0
PAC                     0
SHO                     0
PAS                     0
DRI                     0
DEF                     0
PHY                     0
Hits                    0
dtype: int64

In [5]:
df['is_on_loan'] = df['Loan Date End'].notna().astype(int)

In [8]:
print(df)

                                               photoUrl  \
0      https://cdn.sofifa.com/players/158/023/21_60.png
1      https://cdn.sofifa.com/players/020/801/21_60.png
2      https://cdn.sofifa.com/players/200/389/21_60.png
3      https://cdn.sofifa.com/players/192/985/21_60.png
4      https://cdn.sofifa.com/players/190/871/21_60.png
...                                                 ...
18974  https://cdn.sofifa.com/players/257/710/21_60.png
18975  https://cdn.sofifa.com/players/258/736/21_60.png
18976  https://cdn.sofifa.com/players/247/223/21_60.png
18977  https://cdn.sofifa.com/players/258/760/21_60.png
18978  https://cdn.sofifa.com/players/255/958/21_60.png

                           LongName  \
0                      Lionel Messi
1      C. Ronaldo dos Santos Aveiro
2                         Jan Oblak
3                   Kevin De Bruyne
4        Neymar da Silva Santos Jr.
...                             ...
18974                Mengxuan Zhang
18975                 Vani Da Silva
18976                        Ao Xia
18977                     Ben Hough
18978                  Mateo Flores

                                               playerUrl Nationality  \
0      http://sofifa.com/player/158023/lionel-messi/2...   Argentina
1      http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal
2      http://sofifa.com/player/200389/jan-oblak/210005/    Slovenia
3      http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium
4      http://sofifa.com/player/190871/neymar-da-silv...      Brazil
...                                                  ...         ...
18974  http://sofifa.com/player/257710/mengxuan-zhang...    China PR
18975  http://sofifa.com/player/258736/vani-da-silva/...     England
18976     http://sofifa.com/player/247223/ao-xia/210005/    China PR
18977  http://sofifa.com/player/258760/ben-hough/210005/     England
18978  http://sofifa.com/player/255958/mateo-flores/2...     Bolivia

      Positions               Name  Age  ↓OVA  POT  \
0      RW ST CF           L. Messi   33    93   93
1         ST LW  Cristiano Ronaldo   35    92   92
2            GK           J. Oblak   27    91   93
3        CAM CM       K. De Bruyne   29    91   91
4        LW CAM          Neymar Jr   28    91   91
...         ...                ...  ...   ...  ...
18974        CB     Zhang Mengxuan   21    47   52
18975        ST        V. Da Silva   17    47   67
18976        CB             Xia Ao   21    47   55
18977        CM           B. Hough   17    47   67
18978       CDM          M. Flores   19    47   63

                                         Team & Contract  ...     D/W   IR  \
0                  \n\n\n\nFC Barcelona\n2004 ~ 2021\n\n  ...     Low  5 ★
1                      \n\n\n\nJuventus\n2018 ~ 2022\n\n  ...     Low  5 ★
2               \n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n  ...  Medium  3 ★
3               \n\n\n\nManchester City\n2015 ~ 2023\n\n  ...    High  4 ★
4           \n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n  ...  Medium  5 ★
...                                                  ...  ...     ...  ...
18974  \n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...  ...     Low  1 ★
18975           \n\n\n\nOldham Athletic\n2020 ~ 2021\n\n  ...  Medium  1 ★
18976                \n\n\n\nWuhan Zall\n2018 ~ 2022\n\n  ...  Medium  1 ★
18977           \n\n\n\nOldham Athletic\n2020 ~ 2021\n\n  ...  Medium  1 ★
18978              \n\n\n\nClub Bolívar\n2020 ~ 2024\n\n  ...  Medium  1 ★

      PAC SHO  PAS DRI  DEF PHY   Hits is_on_loan
0      85  92   91  95   38  65  \n372          0
1      89  93   81  89   35  77  \n344          0
2      87  92   78  90   52  90   \n86          0
3      76  86   93  88   64  78  \n163          0
4      91  85   86  94   36  59  \n273          0
...    ..  ..  ...  ..  ...  ..    ...        ...
18974  58  23   26  27   50  48    \n2          0
18975  70  46   40  53   16  40    \n3          0
18976  64  28   26  38   48  51    \n3          0
18977  64  40   48  49   35  45    \n5          0
18978  57  32   43  48   44  49    \n2          0

[18979 rows x 78 columns]

In [6]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [29]:
df

,LongName,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,is_on_loan
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",...,Low,5 ★,85,92,91,95,38,65,\n372,0
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",...,Low,5 ★,89,93,81,89,35,77,\n344,0
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",...,Medium,3 ★,87,92,78,90,52,90,\n86,0
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",...,High,4 ★,76,86,93,88,64,78,\n163,0
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",...,Medium,5 ★,91,85,86,94,36,59,\n273,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",...,Low,1 ★,58,23,26,27,50,48,\n2,0
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",...,Medium,1 ★,70,46,40,53,16,40,\n3,0
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",...,Medium,1 ★,64,28,26,38,48,51,\n3,0
18977,Ben Hough,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",...,Medium,1 ★,64,40,48,49,35,45,\n5,0
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",...,Medium,1 ★,57,32,43,48,44,49,\n2,0

In [35]:
del df['is_permanent']

In [36]:
df

,LongName,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,is_on_loan
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",...,Low,5 ★,85,92,91,95,38,65,\n372,0
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",...,Low,5 ★,89,93,81,89,35,77,\n344,0
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",...,Medium,3 ★,87,92,78,90,52,90,\n86,0
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",...,High,4 ★,76,86,93,88,64,78,\n163,0
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",...,Medium,5 ★,91,85,86,94,36,59,\n273,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",...,Low,1 ★,58,23,26,27,50,48,\n2,0
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",...,Medium,1 ★,70,46,40,53,16,40,\n3,0
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",...,Medium,1 ★,64,28,26,38,48,51,\n3,0
18977,Ben Hough,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",...,Medium,1 ★,64,40,48,49,35,45,\n5,0
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",...,Medium,1 ★,57,32,43,48,44,49,\n2,0

In [37]:
del df['Loan Date End']

In [38]:
df

,LongName,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,is_on_loan
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",...,Low,5 ★,85,92,91,95,38,65,\n372,0
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",...,Low,5 ★,89,93,81,89,35,77,\n344,0
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",...,Medium,3 ★,87,92,78,90,52,90,\n86,0
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",...,High,4 ★,76,86,93,88,64,78,\n163,0
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",...,Medium,5 ★,91,85,86,94,36,59,\n273,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,Mengxuan Zhang,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",...,Low,1 ★,58,23,26,27,50,48,\n2,0
18975,Vani Da Silva,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",...,Medium,1 ★,70,46,40,53,16,40,\n3,0
18976,Ao Xia,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",...,Medium,1 ★,64,28,26,38,48,51,\n3,0
18977,Ben Hough,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",...,Medium,1 ★,64,40,48,49,35,45,\n5,0
18978,Mateo Flores,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",...,Medium,1 ★,57,32,43,48,44,49,\n2,0

In [42]:
df.to_csv('/Users/olatundeolasunkanmi/Downloads/archive (3).zip_1/fifa_cleaned.csv')